### ISSUE TITLE
[Road Map] New Release

### ISSUE THREAD

**Issue by UlisesGascon** [yeoman/generator-webapp#759]
Hi all!

I opened this issue to keep tracking and an open discussion about the next release features and priorities.

### New features & refactors
- [x] Upgrade outdated dependencies in the generated project **PR:#762**
- [x] Upgrade outdated dependencies in the generator  **PR:#760**
- [ ] Let's improve testing in the generated project
  - [x] Improve the prompt message from Mocha generator #545
  - [x] Allow no test-framework to be used #457
  - [ ] Refactor Jasmine (remove sub-generator)
  - [ ] Refactor Mocha (remove sub-generator)
  - [x] Add jest support #615
  - [ ] Add ava support #521
  - [x] Add Cypress support for e2e testing
- [ ] Let's add a `readme.md` in generated project with relevant info (tasks, etc..) #587
- [ ] Add support to CLI no-interaction install #567 & #458

### Bugs to be fixed
- [ ] Even though Yarn is detected, it creates a npm lockfile #747
- [x] Husky tasks needs to be compatible with NPM and Yarn **PR:#761**
- [x] Update `travis.yml` in order to remove compatibility with Node@6 and add support for Node@12. [Test fall with yarn](https://travis-ci.org/yeoman/generator-webapp/jobs/540656581) **PR:#761**

**Comment by UlisesGascon** [comment]
I will open a PR for the testing part soon, also for dependencies ;-)

**Comment by UlisesGascon** [comment]
@silvenon .. what do you think about this testing workflow? Open to discussion for all of you as well! 😉 
![test_demo](https://user-images.githubusercontent.com/5110813/58906337-ff5a2a80-870b-11e9-9399-82c891c04161.gif)

I will improve the Unit testing with a real testing example (Mocha, Jest, Ava & Jasmine), as well I will cover the example with Cypress for e2e.

_Note: You can ignore the creation files log, as this is only a test for the workflow and not a real implementation yet_

**Comment by silvenon** [comment]
Btw, I updated the name of the milestone to v4.0.0 because so far we have pre-releases, which means that the next stable release will be v4.0.0.

**Comment by silvenon** [comment]
> what do you think about this testing workflow?

I like it!

**Comment by UlisesGascon** [comment]
Awesome! v4.0 then :-)

I will prepare the PR asap 🎉

**Comment by silvenon** [comment]
@UlisesGascon could you explain these two tasks?

> - [ ] Refactor Jasmine (remove sub-generator)
> - [ ] Refactor Mocha (remove sub-generator)

Are they referring to a discussion we had somewhere?

**Comment by silvenon** [comment]
I'd also remove the AVA task for v4.0.0 and leave it for v4.1.0, if you agree. Because it's a new feature that requires creating a new generator, and since this doesn't appear to be a highly requested feature I suggest not blocking a stable release of generator-webapp because of this.

**Comment by UlisesGascon** [comment]
@silvenon and interested people... can we move the discussion to PR #763? I think that it will be easier to discuss with some code ^^
